// src/templates/CompactTemplate.tsx
import type { Resume, SectionKey } from "../types/resume";
import {
  FONT_SIZE_PX,
  formatDateRange,
  hasContent,
  type TemplateProps,
} from "./shared";

function SectionTitle({ title, accent }: { title: string; accent: string }) {
  return (
    <h2
      style={{
        margin: "0.6em 0 0.2em",
        fontSize: "1em",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: "0.1em",
        color: accent,
      }}
    >
      {title}
    </h2>
  );
}

function renderSection(r: Resume, key: SectionKey, accent: string) {
  if (!hasContent(r, key)) return null;
  switch (key) {
    case "summary":
      return (
        <section key={key}>
          <SectionTitle title="Summary" accent={accent} />
          <p style={{ margin: 0 }}>{r.personal.summary}</p>
        </section>
      );
    case "experience":
      return (
        <section key={key}>
          <SectionTitle title="Experience" accent={accent} />
          {r.experience.map((e) => (
            <div key={e.id} style={{ marginBottom: "0.45em" }}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: "0.75em",
                }}
              >
                <div>
                  <span style={{ fontWeight: 700 }}>{e.role}</span>
                  {e.company ? `, ${e.company}` : ""}
                  {e.location ? ` — ${e.location}` : ""}
                </div>
                <div style={{ whiteSpace: "nowrap", color: "#475569" }}>
                  {formatDateRange(e.startDate, e.endDate, e.current)}
                </div>
              </div>
              {e.bullets.filter((b) => b.trim()).length > 0 && (
                <ul style={{ margin: "0.1em 0 0", paddingLeft: "1em" }}>
                  {e.bullets
                    .filter((b) => b.trim())
                    .map((b, i) => (
                      <li key={i}>{b}</li>
                    ))}
                </ul>
              )}
            </div>
          ))}
        </section>
      );
    case "education":
      return (
        <section key={key}>
          <SectionTitle title="Education" accent={accent} />
          {r.education.map((e) => (
            <div
              key={e.id}
              style={{
                display: "flex",
                justifyContent: "space-between",
                gap: "0.75em",
              }}
            >
              <div>
                <span style={{ fontWeight: 700 }}>{e.school}</span>
                {" — "}
                {[e.degree, e.field].filter(Boolean).join(", ")}
                {e.location ? ` • ${e.location}` : ""}
                {e.details ? `. ${e.details}` : ""}
              </div>
              <div style={{ whiteSpace: "nowrap", color: "#475569" }}>
                {formatDateRange(e.startDate, e.endDate, false)}
              </div>
            </div>
          ))}
        </section>
      );
    case "projects":
      return (
        <section key={key}>
          <SectionTitle title="Projects" accent={accent} />
          {r.projects.map((p) => (
            <div key={p.id}>
              <span style={{ fontWeight: 700 }}>{p.name}</span>
              {p.link ? ` — ${p.link}` : ""}
              {p.description ? `. ${p.description}` : ""}
            </div>
          ))}
        </section>
      );
    case "skills":
      return (
        <section key={key}>
          <SectionTitle title="Skills" accent={accent} />
          {r.skills.map((g) => (
            <div key={g.id}>
              <span style={{ fontWeight: 700 }}>{g.category}:</span> {g.items}
            </div>
          ))}
        </section>
      );
    case "certifications":
      return (
        <section key={key}>
          <SectionTitle title="Certifications" accent={accent} />
          {r.certifications.map((c) => (
            <div key={c.id}>
              <span style={{ fontWeight: 700 }}>{c.name}</span>
              {c.issuer ? `, ${c.issuer}` : ""}
              {c.date ? ` (${c.date})` : ""}
            </div>
          ))}
        </section>
      );
    case "languages":
      return (
        <section key={key}>
          <SectionTitle title="Languages" accent={accent} />
          <div>
            {r.languages
              .map((l) => `${l.name}${l.level ? ` (${l.level})` : ""}`)
              .join(", ")}
          </div>
        </section>
      );
  }
}

export default function CompactTemplate({ resume }: TemplateProps) {
  const { design, personal } = resume;
  const accent = design.accentColor;
  const fontPx = FONT_SIZE_PX[design.fontSize];
  const fontFamily =
    design.fontFamily === "serif" ? "var(--font-serif)" : "var(--font-sans)";

  const contacts = [
    personal.email,
    personal.phone,
    personal.location,
    personal.website,
    personal.linkedin,
    personal.github,
  ].filter((x) => x && x.trim());

  return (
    <div
      style={{
        fontFamily,
        fontSize: `${fontPx}pt`,
        lineHeight: 1.35,
        color: "#0f172a",
        padding: "0.55in 0.65in",
      }}
    >
      <header
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-end",
          gap: "1em",
          borderBottom: `2px solid ${accent}`,
          paddingBottom: "0.35em",
        }}
      >
        <div>
          <h1 style={{ margin: 0, fontSize: "1.7em", fontWeight: 700 }}>
            {personal.fullName || "Your Name"}
          </h1>
          {personal.title && (
            <div style={{ color: "#475569" }}>{personal.title}</div>
          )}
        </div>
        <div
          style={{
            fontSize: "0.85em",
            color: "#475569",
            textAlign: "right",
            display: "flex",
            flexDirection: "column",
          }}
        >
          {contacts.map((c, i) => (
            <span key={i}>{c}</span>
          ))}
        </div>
      </header>
      {resume.sections.map((key) => renderSection(resume, key, accent))}
    </div>
  );
}

// src/templates/CompactTemplate.vue
<template>
  <div
    :style="{
      fontFamily,
      fontSize: `${fontPx}pt`,
      lineHeight: 1.35,
      color: '#0f172a',
      padding: '0.55in 0.65in',
    }"
  >
    <header
      style="display: flex; justify-content: space-between; align-items: flex-end; gap: 1em; border-bottom: 2px solid; padding-bottom: 0.35em"
      :style="{ borderBottomColor: accent }"
    >
      <div>
        <h1 style="margin: 0; font-size: 1.7em; font-weight: 700">
          {{ personal.fullName || "Your Name" }}
        </h1>
        <div
          v-if="personal.title"
          style="color: #475569"
        >
          {{ personal.title }}
        </div>
      </div>
      <div
        style="font-size: 0.85em; color: #475569; text-align: right; display: flex; flex-direction: column"
      >
        <span
          v-for="(c, i) in contacts"
          :key="i"
        >{{ c }}</span>
      </div>
    </header>

    <template
      v-for="key in resume.sections"
      :key="key"
    >
      <section v-if="hasContent(resume, key)">
        <h2
          :style="{
            margin: '0.6em 0 0.2em',
            fontSize: '1em',
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '0.1em',
            color: accent,
          }"
        >
          {{ getSectionTitle(key) }}
        </h2>

        <!-- Summary -->
        <template v-if="key === 'summary'">
          <p style="margin: 0">
            {{ resume.personal.summary }}
          </p>
        </template>

        <!-- Experience -->
        <template v-else-if="key === 'experience'">
          <div
            v-for="e in resume.experience"
            :key="e.id"
            style="margin-bottom: 0.45em"
          >
            <div style="display: flex; justify-content: space-between; gap: 0.75em">
              <div>
                <span style="font-weight: 700">{{ e.role }}</span>
                {{ e.company ? `, ${e.company}` : "" }}
                {{ e.location ? ` — ${e.location}` : "" }}
              </div>
              <div style="white-space: nowrap; color: #475569">
                {{ formatDateRange(e.startDate, e.endDate, e.current) }}
              </div>
            </div>
            <ul
              v-if="e.bullets.filter(b => b.trim()).length > 0"
              style="margin: 0.1em 0 0; padding-left: 1em"
            >
              <li
                v-for="(b, i) in e.bullets.filter(b => b.trim())"
                :key="i"
              >
                {{ b }}
              </li>
            </ul>
          </div>
        </template>

        <!-- Education -->
        <template v-else-if="key === 'education'">
          <div
            v-for="e in resume.education"
            :key="e.id"
            style="display: flex; justify-content: space-between; gap: 0.75em"
          >
            <div>
              <span style="font-weight: 700">{{ e.school }}</span>
              — {{ [e.degree, e.field].filter(Boolean).join(", ") }}
              {{ e.location ? ` • ${e.location}` : "" }}
              {{ e.details ? `. ${e.details}` : "" }}
            </div>
            <div style="white-space: nowrap; color: #475569">
              {{ formatDateRange(e.startDate, e.endDate, false) }}
            </div>
          </div>
        </template>

        <!-- Projects -->
        <template v-else-if="key === 'projects'">
          <div
            v-for="p in resume.projects"
            :key="p.id"
          >
            <span style="font-weight: 700">{{ p.name }}</span>
            {{ p.link ? ` — ${p.link}` : "" }}
            {{ p.description ? `. ${p.description}` : "" }}
          </div>
        </template>

        <!-- Skills -->
        <template v-else-if="key === 'skills'">
          <div
            v-for="g in resume.skills"
            :key="g.id"
          >
            <span style="font-weight: 700">{{ g.category }}:</span> {{ g.items }}
          </div>
        </template>

        <!-- Certifications -->
        <template v-else-if="key === 'certifications'">
          <div
            v-for="c in resume.certifications"
            :key="c.id"
          >
            <span style="font-weight: 700">{{ c.name }}</span>
            {{ c.issuer ? `, ${c.issuer}` : "" }}
            {{ c.date ? ` (${c.date})` : "" }}
          </div>
        </template>

        <!-- Languages -->
        <template v-else-if="key === 'languages'">
          <div>
            {{ resume.languages.map(l => `${l.name}${l.level ? ` (${l.level})` : ""}`).join(", ") }}
          </div>
        </template>
      </section>
    </template>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import type { Resume, SectionKey } from '../types/resume';
import { FONT_SIZE_PX, formatDateRange, hasContent } from './shared';

export default defineComponent({
  name: 'CompactTemplate',
  props: {
    resume: { type: Object as () => Resume, required: true }
  },
  computed: {
    personal() { return this.resume.personal; },
    design() { return this.resume.design; },
    accent() { return this.design.accentColor; },
    fontPx() { return FONT_SIZE_PX[this.design.fontSize]; },
    fontFamily() {
      return this.design.fontFamily === "serif" ? "var(--font-serif)" : "var(--font-sans)";
    },
    contacts() {
      const p = this.personal;
      return [p.email, p.phone, p.location, p.website, p.linkedin, p.github].filter(
        (x) => x && x.trim(),
      );
    }
  },
  methods: {
    hasContent,
    formatDateRange,
    getSectionTitle(key: SectionKey) {
      const titles: Record<SectionKey, string> = {
        summary: "Summary",
        experience: "Experience",
        education: "Education",
        projects: "Projects",
        skills: "Skills",
        certifications: "Certifications",
        languages: "Languages",
      };
      return titles[key];
    }
  }
});
</script>
