// src/templates/TwoColumnTemplate.vue
<template>
  <div
    :style="{
      fontFamily,
      fontSize: `${fontPx}pt`,
      lineHeight: 1.4,
      color: '#0f172a',
      display: 'grid',
      gridTemplateColumns: '3.1in 1fr',
      minHeight: '11in',
    }"
  >
    <!-- Left Sidebar -->
    <aside
      style="background: #0f172a; color: white; padding: 0.6in 0.4in; align-self: stretch"
    >
      <div style="margin-bottom: 0.6em">
        <h1 style="margin: 0; font-size: 1.5em; font-weight: 800; color: white">
          {{ personal.fullName || "Your Name" }}
        </h1>
        <div
          v-if="personal.title"
          :style="{ color: accent, fontWeight: 600 }"
        >
          {{ personal.title }}
        </div>
      </div>

      <section v-if="contacts.length > 0">
        <h2 style="margin: 0.9em 0 0.3em; font-size: 0.95em; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #f8fafc">
          Contact
        </h2>
        <div
          v-for="(c, i) in contacts"
          :key="i"
          style="color: #cbd5e1; word-break: break-word"
        >
          {{ c }}
        </div>
      </section>

      <template
        v-for="key in leftOrdered"
        :key="key"
      >
        <section v-if="hasContent(resume, key)">
          <h2 style="margin: 0.9em 0 0.3em; font-size: 0.95em; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #f8fafc">
            {{ getLeftSectionTitle(key) }}
          </h2>

          <template v-if="key === 'skills'">
            <div
              v-for="g in resume.skills"
              :key="g.id"
              style="margin-bottom: 0.35em"
            >
              <div style="font-weight: 700">
                {{ g.category }}
              </div>
              <div style="color: #cbd5e1">
                {{ g.items }}
              </div>
            </div>
          </template>

          <template v-else-if="key === 'education'">
            <div
              v-for="e in resume.education"
              :key="e.id"
              style="margin-bottom: 0.45em"
            >
              <div style="font-weight: 700">
                {{ e.school }}
              </div>
              <div style="color: #cbd5e1">
                {{ [e.degree, e.field].filter(Boolean).join(", ") }}{{ e.location ? ` • ${e.location}` : "" }}
              </div>
              <div style="color: #94a3b8; font-size: 0.85em">
                {{ formatDateRange(e.startDate, e.endDate, false) }}
              </div>
              <div
                v-if="e.details"
                style="color: #cbd5e1; font-size: 0.88em"
              >
                {{ e.details }}
              </div>
            </div>
          </template>

          <template v-else-if="key === 'certifications'">
            <div
              v-for="c in resume.certifications"
              :key="c.id"
              style="margin-bottom: 0.3em"
            >
              <div style="font-weight: 700">
                {{ c.name }}
              </div>
              <div style="color: #cbd5e1; font-size: 0.88em">
                {{ c.issuer }}{{ c.date ? ` · ${c.date}` : "" }}
              </div>
            </div>
          </template>

          <template v-else-if="key === 'languages'">
            <div
              v-for="l in resume.languages"
              :key="l.id"
              style="color: #cbd5e1"
            >
              <span style="font-weight: 700; color: white">{{ l.name }}</span>{{ l.level ? ` — ${l.level}` : "" }}
            </div>
          </template>
        </section>
      </template>
    </aside>

    <!-- Right Main Content -->
    <main style="padding: 0.55in 0.55in">
      <template
        v-for="key in rightOrdered"
        :key="key"
      >
        <section v-if="hasContent(resume, key)">
          <h2
            :style="{
              margin: '0.9em 0 0.3em',
              fontSize: '1.05em',
              fontWeight: 700,
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
              color: accent,
              borderBottom: `1px solid ${accent}`,
              paddingBottom: '2px',
            }"
          >
            {{ getRightSectionTitle(key) }}
          </h2>

          <template v-if="key === 'summary'">
            <p style="margin: 0">
              {{ resume.personal.summary }}
            </p>
          </template>

          <template v-else-if="key === 'experience'">
            <div
              v-for="e in resume.experience"
              :key="e.id"
              style="margin-bottom: 0.65em"
            >
              <div style="font-weight: 700; font-size: 1.02em">
                {{ e.role }}
              </div>
              <div style="display: flex; justify-content: space-between; gap: 0.75em; color: #475569">
                <div>{{ e.company }}{{ e.location ? ` · ${e.location}` : "" }}</div>
                <div style="white-space: nowrap">
                  {{ formatDateRange(e.startDate, e.endDate, e.current) }}
                </div>
              </div>
              <ul
                v-if="e.bullets.filter(b => b.trim()).length > 0"
                style="margin: 0.2em 0 0; padding-left: 1.15em"
              >
                <li
                  v-for="(b, i) in e.bullets.filter(b => b.trim())"
                  :key="i"
                >
                  {{ b }}
                </li>
              </ul>
            </div>
          </template>

          <template v-else-if="key === 'projects'">
            <div
              v-for="p in resume.projects"
              :key="p.id"
              style="margin-bottom: 0.4em"
            >
              <div style="display: flex; justify-content: space-between; gap: 0.75em">
                <div style="font-weight: 700">
                  {{ p.name }}
                </div>
                <div
                  v-if="p.link"
                  :style="{ color: accent }"
                >
                  {{ p.link }}
                </div>
              </div>
              <div v-if="p.description">
                {{ p.description }}
              </div>
              <ul
                v-if="p.bullets.filter(b => b.trim()).length > 0"
                style="margin: 0.2em 0 0; padding-left: 1.15em"
              >
                <li
                  v-for="(b, i) in p.bullets.filter(b => b.trim())"
                  :key="i"
                >
                  {{ b }}
                </li>
              </ul>
            </div>
          </template>
        </section>
      </template>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import type { Resume, SectionKey } from '../types/resume';
import { FONT_SIZE_PX, formatDateRange, hasContent } from './shared';

const LEFT_KEYS: SectionKey[] = ["skills", "education", "certifications", "languages"];
const RIGHT_KEYS: SectionKey[] = ["summary", "experience", "projects"];

export default defineComponent({
  name: 'TwoColumnTemplate',
  props: {
    resume: { type: Object as () => Resume, required: true }
  },
  computed: {
    personal() { return this.resume.personal; },
    design() { return this.resume.design; },
    accent() { return this.design.accentColor; },
    fontPx() { return FONT_SIZE_PX[this.design.fontSize]; },
    fontFamily() {
      return this.design.fontFamily === "serif" ? "var(--font-serif)" : "var(--font-sans)";
    },
    contacts() {
      const p = this.personal;
      return [p.email, p.phone, p.location, p.website, p.linkedin, p.github].filter(
        (x) => x && x.trim(),
      );
    },
    leftOrdered() { return this.resume.sections.filter((k) => LEFT_KEYS.includes(k)); },
    rightOrdered() { return this.resume.sections.filter((k) => RIGHT_KEYS.includes(k)); }
  },
  methods: {
    hasContent,
    formatDateRange,
    getLeftSectionTitle(key: SectionKey) {
      const titles: Record<string, string> = {
        skills: "Skills",
        education: "Education",
        certifications: "Certifications",
        languages: "Languages"
      };
      return titles[key] || key;
    },
    getRightSectionTitle(key: SectionKey) {
      const titles: Record<string, string> = {
        summary: "Profile",
        experience: "Experience",
        projects: "Projects"
      };
      return titles[key] || key;
    }
  }
});
</script>

// src/templates/TwoColumnTemplate.tsx
import type { Resume, SectionKey } from "../types/resume";
import {
  FONT_SIZE_PX,
  formatDateRange,
  hasContent,
  type TemplateProps,
} from "./shared";

const LEFT_KEYS: SectionKey[] = ["skills", "education", "certifications", "languages"];
const RIGHT_KEYS: SectionKey[] = ["summary", "experience", "projects"];

function SidebarTitle({ title }: { title: string }) {
  return (
    <h2
      style={{
        margin: "0.9em 0 0.3em",
        fontSize: "0.95em",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: "0.1em",
        color: "#f8fafc",
      }}
    >
      {title}
    </h2>
  );
}

function MainTitle({ title, accent }: { title: string; accent: string }) {
  return (
    <h2
      style={{
        margin: "0.9em 0 0.3em",
        fontSize: "1.05em",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        color: accent,
        borderBottom: `1px solid ${accent}`,
        paddingBottom: "2px",
      }}
    >
      {title}
    </h2>
  );
}

function renderLeftSection(r: Resume, key: SectionKey) {
  if (!hasContent(r, key)) return null;
  switch (key) {
    case "skills":
      return (
        <section key={key}>
          <SidebarTitle title="Skills" />
          {r.skills.map((g) => (
            <div key={g.id} style={{ marginBottom: "0.35em" }}>
              <div style={{ fontWeight: 700 }}>{g.category}</div>
              <div style={{ color: "#cbd5e1" }}>{g.items}</div>
            </div>
          ))}
        </section>
      );
    case "education":
      return (
        <section key={key}>
          <SidebarTitle title="Education" />
          {r.education.map((e) => (
            <div key={e.id} style={{ marginBottom: "0.45em" }}>
              <div style={{ fontWeight: 700 }}>{e.school}</div>
              <div style={{ color: "#cbd5e1" }}>
                {[e.degree, e.field].filter(Boolean).join(", ")}
                {e.location ? ` • ${e.location}` : ""}
              </div>
              <div style={{ color: "#94a3b8", fontSize: "0.85em" }}>
                {formatDateRange(e.startDate, e.endDate, false)}
              </div>
              {e.details && (
                <div style={{ color: "#cbd5e1", fontSize: "0.88em" }}>{e.details}</div>
              )}
            </div>
          ))}
        </section>
      );
    case "certifications":
      return (
        <section key={key}>
          <SidebarTitle title="Certifications" />
          {r.certifications.map((c) => (
            <div key={c.id} style={{ marginBottom: "0.3em" }}>
              <div style={{ fontWeight: 700 }}>{c.name}</div>
              <div style={{ color: "#cbd5e1", fontSize: "0.88em" }}>
                {c.issuer}
                {c.date ? ` · ${c.date}` : ""}
              </div>
            </div>
          ))}
        </section>
      );
    case "languages":
      return (
        <section key={key}>
          <SidebarTitle title="Languages" />
          {r.languages.map((l) => (
            <div key={l.id} style={{ color: "#cbd5e1" }}>
              <span style={{ fontWeight: 700, color: "white" }}>{l.name}</span>
              {l.level ? ` — ${l.level}` : ""}
            </div>
          ))}
        </section>
      );
    default:
      return null;
  }
}

function renderRightSection(r: Resume, key: SectionKey, accent: string) {
  if (!hasContent(r, key)) return null;
  switch (key) {
    case "summary":
      return (
        <section key={key}>
          <MainTitle title="Profile" accent={accent} />
          <p style={{ margin: 0 }}>{r.personal.summary}</p>
        </section>
      );
    case "experience":
      return (
        <section key={key}>
          <MainTitle title="Experience" accent={accent} />
          {r.experience.map((e) => (
            <div key={e.id} style={{ marginBottom: "0.65em" }}>
              <div style={{ fontWeight: 700, fontSize: "1.02em" }}>{e.role}</div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: "0.75em",
                  color: "#475569",
                }}
              >
                <div>
                  {e.company}
                  {e.location ? ` · ${e.location}` : ""}
                </div>
                <div style={{ whiteSpace: "nowrap" }}>
                  {formatDateRange(e.startDate, e.endDate, e.current)}
                </div>
              </div>
              {e.bullets.filter((b) => b.trim()).length > 0 && (
                <ul style={{ margin: "0.2em 0 0", paddingLeft: "1.15em" }}>
                  {e.bullets
                    .filter((b) => b.trim())
                    .map((b, i) => (
                      <li key={i}>{b}</li>
                    ))}
                </ul>
              )}
            </div>
          ))}
        </section>
      );
    case "projects":
      return (
        <section key={key}>
          <MainTitle title="Projects" accent={accent} />
          {r.projects.map((p) => (
            <div key={p.id} style={{ marginBottom: "0.4em" }}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: "0.75em",
                }}
              >
                <div style={{ fontWeight: 700 }}>{p.name}</div>
                {p.link && <div style={{ color: accent }}>{p.link}</div>}
              </div>
              {p.description && <div>{p.description}</div>}
              {p.bullets.filter((b) => b.trim()).length > 0 && (
                <ul style={{ margin: "0.2em 0 0", paddingLeft: "1.15em" }}>
                  {p.bullets
                    .filter((b) => b.trim())
                    .map((b, i) => (
                      <li key={i}>{b}</li>
                    ))}
                </ul>
              )}
            </div>
          ))}
        </section>
      );
    default:
      return null;
  }
}

export default function TwoColumnTemplate({ resume }: TemplateProps) {
  const { design, personal } = resume;
  const accent = design.accentColor;
  const fontPx = FONT_SIZE_PX[design.fontSize];
  const fontFamily =
    design.fontFamily === "serif" ? "var(--font-serif)" : "var(--font-sans)";

  const contacts = [
    personal.email,
    personal.phone,
    personal.location,
    personal.website,
    personal.linkedin,
    personal.github,
  ].filter((x) => x && x.trim());

  const leftOrdered = resume.sections.filter((k) => LEFT_KEYS.includes(k));
  const rightOrdered = resume.sections.filter((k) => RIGHT_KEYS.includes(k));

  return (
    <div
      style={{
        fontFamily,
        fontSize: `${fontPx}pt`,
        lineHeight: 1.4,
        color: "#0f172a",
        display: "grid",
        gridTemplateColumns: "3.1in 1fr",
        minHeight: "100%",
      }}
    >
      <aside
        style={{
          background: "#0f172a",
          color: "white",
          padding: "0.6in 0.4in",
          alignSelf: "stretch",   
        }}
      >
        <div style={{ marginBottom: "0.6em" }}>
          <h1 style={{ margin: 0, fontSize: "1.5em", fontWeight: 800, color: "white" }}>
            {personal.fullName || "Your Name"}
          </h1>
          {personal.title && (
            <div style={{ color: accent, fontWeight: 600 }}>{personal.title}</div>
          )}
        </div>
        {contacts.length > 0 && (
          <section>
            <SidebarTitle title="Contact" />
            {contacts.map((c, i) => (
              <div key={i} style={{ color: "#cbd5e1", wordBreak: "break-word" }}>
                {c}
              </div>
            ))}
          </section>
        )}
        {leftOrdered.map((k) => renderLeftSection(resume, k))}
      </aside>
      <main style={{ padding: "0.55in 0.55in" }}>
        {rightOrdered.map((k) => renderRightSection(resume, k, accent))}
      </main>
    </div>
  );
}
