// src/components/form/sections/PersonalSection.tsx
import type { Resume } from "../../../types/resume";
import { Field, TextArea, TextInput } from "../FormField";
import SectionCard from "../SectionCard";

interface Props {
  resume: Resume;
  update: (updater: (r: Resume) => Resume) => void;
}

export default function PersonalSection({ resume, update }: Props) {
  const p = resume.personal;
  const set = <K extends keyof typeof p>(key: K, value: (typeof p)[K]) =>
    update((r) => ({ ...r, personal: { ...r.personal, [key]: value } }));

  return (
    <SectionCard
      title="Personal details"
      subtitle="Your name, title, and contact info"
      defaultOpen
    >
      <div className="grid gap-3 sm:grid-cols-2">
        <Field label="Full name">
          <TextInput
            value={p.fullName}
            onChange={(e) => set("fullName", e.target.value)}
            placeholder="Alex Morgan"
          />
        </Field>
        <Field label="Professional title">
          <TextInput
            value={p.title}
            onChange={(e) => set("title", e.target.value)}
            placeholder="Senior Software Engineer"
          />
        </Field>
        <Field label="Email">
          <TextInput
            value={p.email}
            onChange={(e) => set("email", e.target.value)}
            placeholder="you@example.com"
          />
        </Field>
        <Field label="Phone">
          <TextInput
            value={p.phone}
            onChange={(e) => set("phone", e.target.value)}
            placeholder="+1 (555) 123-4567"
          />
        </Field>
        <Field label="Location">
          <TextInput
            value={p.location}
            onChange={(e) => set("location", e.target.value)}
            placeholder="San Francisco, CA"
          />
        </Field>
        <Field label="Website">
          <TextInput
            value={p.website}
            onChange={(e) => set("website", e.target.value)}
            placeholder="yourname.dev"
          />
        </Field>
        <Field label="LinkedIn">
          <TextInput
            value={p.linkedin}
            onChange={(e) => set("linkedin", e.target.value)}
            placeholder="linkedin.com/in/you"
          />
        </Field>
        <Field label="GitHub">
          <TextInput
            value={p.github}
            onChange={(e) => set("github", e.target.value)}
            placeholder="github.com/you"
          />
        </Field>
      </div>
    </SectionCard>
  );
}

// src/components/form/sections/PersonalSection.vue
<template>
  <SectionCard
    title="Personal details"
    subtitle="Your name, title, and contact info"
    :default-open="true"
  >
    <div class="grid gap-3 sm:grid-cols-2">
      <Field label="Full name">
        <TextInput
          :model-value="p.fullName"
          placeholder="Alex Morgan"
          @update:model-value="set('fullName', $event)"
        />
      </Field>
      <Field label="Professional title">
        <TextInput
          :model-value="p.title"
          placeholder="Senior Software Engineer"
          @update:model-value="set('title', $event)"
        />
      </Field>
      <Field label="Email">
        <TextInput
          :model-value="p.email"
          placeholder="you@example.com"
          @update:model-value="set('email', $event)"
        />
      </Field>
      <Field label="Phone">
        <TextInput
          :model-value="p.phone"
          placeholder="+1 (555) 123-4567"
          @update:model-value="set('phone', $event)"
        />
      </Field>
      <Field label="Location">
        <TextInput
          :model-value="p.location"
          placeholder="San Francisco, CA"
          @update:model-value="set('location', $event)"
        />
      </Field>
      <Field label="Website">
        <TextInput
          :model-value="p.website"
          placeholder="yourname.dev"
          @update:model-value="set('website', $event)"
        />
      </Field>
      <Field label="LinkedIn">
        <TextInput
          :model-value="p.linkedin"
          placeholder="linkedin.com/in/you"
          @update:model-value="set('linkedin', $event)"
        />
      </Field>
      <Field label="GitHub">
        <TextInput
          :model-value="p.github"
          placeholder="github.com/you"
          @update:model-value="set('github', $event)"
        />
      </Field>
    </div>
  </SectionCard>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import type { Resume } from '../../../types/resume';
import Field from '../Field.vue';
import TextInput from '../TextInput.vue';
import SectionCard from '../SectionCard.vue';

export default defineComponent({
  name: 'PersonalSection',
  components: {
    Field,
    TextInput,
    SectionCard
  },
  props: {
    resume: { type: Object as () => Resume, required: true }
  },
  emits: ['update'],
  computed: {
    p() { return this.resume.personal; }
  },
  methods: {
    set(key: string, value: string) {
      this.$emit('update', (r: Resume) => ({
        ...r,
        personal: { ...r.personal, [key]: value }
      }));
    }
  }
});
</script>
