// src/components/ResumePage.vue
<template>
  <div
    :data-print-target="printable ? 'true' : undefined"
    :class="['bg-white shadow-md', className]"
    :style="{
      width: '8.5in',
      minHeight: printable ? 'auto' : '11in',
      margin: '0 auto',
      boxSizing: 'border-box',
      overflow: printable ? 'visible' : 'hidden',
    }"
  >
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'ResumePage',
  props: {
    className: { type: String, default: '' },
    printable: { type: Boolean, default: false }
  }
});
</script>

// src/components/ResumePage.tsx
import { type ReactNode, forwardRef } from "react";

/**
 * A fixed US-letter-sized page container. Uses a single 8.5in x 11in canvas
 * so the preview matches the printed PDF exactly.
 */
const ResumePage = forwardRef<
  HTMLDivElement,
  { children: ReactNode; className?: string; printable?: boolean }
>(({ children, className = "", printable = false }, ref) => {
    return (
      <div
        ref={ref}
        data-print-target={printable ? "true" : undefined}
        className={"bg-white shadow-md " + className}
        style={{
          width: "8.5in",
          minHeight: printable ? "auto" : "11in",
          margin: "0 auto",
          boxSizing: "border-box",
          overflow: printable ? "visible" : "hidden", 
        }}
      >
        {children}
      </div>
    );
  },
);
ResumePage.displayName = "ResumePage";

export default ResumePage;
